### PR TITLE
Fix type replacement issues

### LINKED ISSUE #10049: Documentation glitch
**Describe the bug**
There are two unresponsive Type links in https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw.html
I would expect GeometryFunction in Options to link to the definition above Options (similar to https://openlayers.org/en/latest/apidoc/module-ol_style_Style.htm ) while PointCoordType within SketchCoordType is showing the wrong module.  Presumably the first is due to the definition order, but the second one?

### PR DESCRIPTION
**Pull request by simonseyock**
Iterate through the comments two times. First collecting all identifiers and then replace them properly.

This fixes https://github.com/openlayers/openlayers/issues/10049

### CODE REVIEW

**Comment by simonseyock** [comment]
The second commit corrects an error where parts of types were matched.
i.e. `PointCoordType` was matched by the expression for `Point`

**Comment by simonseyock** [comment]
This PR seems to have problems with @fires

**Comment by simonseyock** [comment]
I have it fixed mostly, but there is still the problem that many event links point to apidoc/module-ol_events_Event-Event.html which does not get generated.
So I am asking myself where it is defined, with a brief search I did not find any typedef. In the current documentation on openlayers.org it is present but is not findable via the search.

See https://openlayers.org/en/latest/apidoc/module-ol_events_Event-BaseEvent.html and https://openlayers.org/en/latest/apidoc/module-ol_events_Event-Event.html

As these two documents only differ in one detail (`ExtentInteractionEvent` instead of `ExtentEvent`), I searched for the term `ExtentInteractionEvent` and did not find it in the source code!

Could it be that the file is somehow a leftover from a previous generation? If that is the case, many types need to be changed from Event to BaseEvent.

This is not covered by typecheck because BaseEvent is a default export and always gets named BaseEvent.

I personally try to avoid default exports all together because it tends to get messy. But this is no change that could be done before v7.

So another way to solve this is in the jsdoc generation to first find out the real class names of every default export and afterwards change all the types accordingly. That means to iterate over the files two times.

**Comment by ahocevar** [comment]
> Could it be that the file is somehow a leftover from a previous generation? If that is the case, many types need to be changed from Event to BaseEvent.

Yes, this is the case. Our website generation process only overwrites files, but does not remove any. So it is better to debug this locally. There is only `module-ol_events_Event-BaseEvent.html`.

> So another way to solve this is in the jsdoc generation to first find out the real class names of every default export and afterwards change all the types accordingly. That means to iterate over the files two times.

This would be the preferred way. But as things are currently related to TypeScript 3.7, a (fragile) workaround would be to name the imports accordingly in OpenLayers. See https://github.com/openlayers/openlayers/pull/10061/files#diff-079b05a573d5011f09c95c02d280ef16

**Comment by simonseyock** [comment]
OK, if this does not occur elsewhere this would fix it. I will look into it.

**Review by ahocevar — APPROVED** [review]

**Pull request merged**
